### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Flecart** [DaddaOperator/Calculator#2]
Purtroppo è 
1. Scritto in Java
2. Ha binari pushati
3. ChatGPT sa fare meglio.

(Ops io non ho detto nulla è stato chatGPT ad obbligarmi.)

**Comment by DaddaOperator** [comment]
Guarda hai assolutamente ragione ahah, però il motivo per cui ho deciso di pubblicarlo è puramente legato ad una funzione di archivio dei progetti che ho fatto durante l'anno e questo era il primissimo dell'anno scorso con Java, non per metterlo in mostra come modello. Per quello pusherò altri progetti più strutturati presto.

**Comment by DaddaRev** [comment]
Guarda hai assolutamente ragione ahah, però il motivo per cui ho deciso di pubblicarlo è puramente legato ad una funzione di archivio dei progetti che ho fatto durante l'anno e questo era il primissimo dell'anno scorso con Java, non per metterlo in mostra come modello. Per quello pusherò altri progetti più strutturati presto.
